spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    defer-datasource-initialization: true
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
logging:
  level:
    org.sky.study: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health

#TODO move to vault
jwt:
  secret-key: my_secret_key
