spring:
  security:
    enabled: false
  thymeleaf:
    cache: false
  main:
    show-banner: false
    elasticsearch:
      uris: http://localhost:9200
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
jwt:
  secret-key: my_secret_key
