-- Insert Admin and user
INSERT INTO USERS (USERNAME, PASSWORD, ROLES) VALUES ('admin', '$2a$10$aOq6wLjD4LBB3h8W/rAmpOcQE2kXB1yPYM2dofiB5YGCS.U.RV.R2', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLES) VALUES ('user', '$2a$10$aOq6wLjD4LBB3h8W/rAmpOcQE2kXB1yPYM2dofiB5YGCS.U.RV.R2', 'USER');

-- Insert Movies (Top 10 IMDb Movies with genre and releaseYear)
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Shawshank Redemption', 'Drama', 1994);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Godfather', 'Crime', 1972);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Dark Knight', 'Action', 2008);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Godfather Part II', 'Crime', 1974);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('12 Angry Men', 'Drama', 1957);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('Schindlers List', 'Biography', 1993);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Lord of the Rings: The Return of the King', 'Fantasy', 2003);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('Pulp Fiction', 'Crime', 1994);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('The Good, the Bad and the Ugly', 'Western', 1966);
INSERT INTO MOVIES (TITLE, GENRE, RELEASE_YEAR) VALUES ('Fight Club', 'Drama', 1999);

-- Insert Ratings (One user rating all 10 movies)
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (9, 1, 1);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (8, 2, 1);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (10, 1, 2);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (9, 2, 2);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (8, 1, 3);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (7, 2, 3);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (9, 1, 4);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (7, 1, 5);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (10, 1, 6);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (8, 1, 7);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (9, 1, 8);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (10, 1, 9);
INSERT INTO RATINGS (SCORE, USER_ID, MOVIE_ID) VALUES (9, 1, 10);